In [3]:
import pandas as pd

In [6]:
movies = pd.read_csv('tmdb_6000_movies.csv')

In [12]:
movies.describe

<bound method NDFrame.describe of          budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
...         ...                                                ...
5793          0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
5794          0  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
5795          0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
5796          0                [{'id': 99, 'name': 'Documentary'}]
5797          0  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...

                                               homepage       id  \
0                           http://www.avatarmovie.com/    19995
1          http://disney.go.com/disneypictures/pirates/      285
2           http://www.sonypictures.com/movies/spectre/   206647
3                    http://www.thedarkknightrises.com/    49026
4                  http://movies.disney.com/john-carter    49529
...                                                 ...      ...
5793     https://www.searchlightpictures.com/flamin-hot   626332
5794                                                NaN  1094319
5795                                                NaN   998623
5796  https://tv.apple.com/movie//umc.cmc.633pbtki99...  1155770
5797                                                NaN   842544

                                               keywords original_language  \
0     [{'id': 1463, 'name': 'culture clash'}, {'id':...                en
1     [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...                en
2     [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...                en
3     [{'id': 849, 'name': 'dc comics'}, {'id': 853,...                en
4     [{'id': 818, 'name': 'based on novel'}, {'id':...                en
...                                                 ...               ...
5793  [{'id': 5565, 'name': 'biography'}, {'id': 967...                en
5794                                                 []                en
5795                                                 []                fr
5796  [{'id': 14618, 'name': 'british spy'}, {'id': ...                en
5797  [{'id': 697, 'name': 'loss of loved one'}, {'i...                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
5793                               Flamin' Hot
5794                              The Best Man
5795                               Drone Games
5796                         The Pigeon Tunnel
5797                               Transfusion

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577
1     Captain Barbossa, long believed to be dead, ha...  139.082615
2     A cryptic message from Bond’s past sends him o...  107.376788
3     Following the death of District Attorney Harve...  112.312950
4     John Carter is a war-weary, former military ca...   43.926995
...                                                 ...         ...
5793  The inspiring true story of Richard Montañez, ...   53.988000
5794  Mercenaries seize control of a remote resort h...   47.740000
5795                                                NaN   27.587000
5796  Academy Award® winner Errol Morris pulls back ...   47.684000
5797  Ryan Logan, a former Special Forces operative,...   51.693000

                                   production_companies  \
0     [{"name": "Ingenious Film Partners", "id": 289...
1     [{"name": "Walt Disney Pictures", "id": 2}, {"...
2     [{"name": "Columbia Pictures", "id": 5}, {"nam...
3     [{"name": "Legendary Pictures", "id": 923}, {"...
4           [{"name": "Walt Disney Pictures", "id": 2}]
...                                                 ...
5793  [{'id': 61377, 'logo_path': '/6IQmmSszsXcxbew2...
5794  [{'id': 76992, 'logo_path': '/mw3j3P8SUQJKLSJQ...
5795  [{'id': 178619, 'logo_path': '/wlyh239wcxFSE7K...
5796  [{'id': 28275, 'logo_path': '/b6VatRipyJYN52xL...
5797  [{'id': 126370, 'logo_path': None, 'name': 'De...

                                   production_countries release_date  \
0     [{"iso_3166_1": "US", "name": "United States o...   2009-12-10
1     [{"iso_3166_1": "US", "name": "United States o...   2007-05-19
2     [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26
3     [{"iso_3166_1": "US", "name": "United States o...   2012-07-16
4     [{"iso_3166_1": "US", "name": "United States o...   2012-03-07
...                                                 ...          ...
5793  [{'iso_3166_1': 'US', 'name': 'United States o...   2023-03-11
5794                                                 []   2023-04-21
5795           [{'iso_3166_1': 'FR', 'name': 'France'}]   2023-10-19
5796   [{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]   2023-10-20
5797  [{'iso_3166_1': 'AU', 'name': 'Australia'}, {'...   2023-01-05

         revenue  runtime                                   spoken_languages  \
0     2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
1      961000000    169.0           [{"iso_639_1": "en", "name": "English"}]
2      880674609    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...
3     1084939099    165.0           [{"iso_639_1": "en", "name": "English"}]
4      284139100    132.0           [{"iso_639_1": "en", "name": "English"}]
...          ...      ...                                                ...
5793           0     99.0  [{'english_name': 'English', 'iso_639_1': 'en'...
5794           0     93.0  [{'english_name': 'English', 'iso_639_1': 'en'...
5795           0      0.0  [{'english_name': 'French', 'iso_639_1': 'fr',...
5796           0     92.0  [{'english_name': 'English', 'iso_639_1': 'en'...
5797           0    105.0  [{'english_name': 'English', 'iso_639_1': 'en'...

        status                                         tagline  \
0     Released                     Enter the World of Pandora.
1     Released  At the end of the world, the adventure begins.
2     Released                           A Plan No One Escapes
3     Released                                 The Legend Ends
4     Released            Lost in our world, found in another.
...        ...                                             ...
5793  Released       The flavor you know. The story you don't.
5794  Released                                             NaN
5795  Released                                             NaN
5796  Released         Stories from the life of John le Carré.
5797  Released                                 Blood is blood.

                                         title  vote_average  vote_count
0                                       Avatar         7.200       11800
1     Pirates of the Caribbean: At World's End         6.900        4500
2                                      Spectre         6.300        4466
3                        The Dark Knight Rises         7.600        9106
4                                  John Carter         6.100        2124
...                                        ...           ...         ...
5793                               Flamin' Hot         8.190         410
5794                              The Best Man         6.167          93
5795                               Drone Games         2.000           1
5796                         The Pigeon Tunnel         7.667           3
5797                               Transfusion         6.133         210

[5798 rows x 20 columns]>

In [13]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [15]:
movies = movies[["id","genres","original_language","title"]]

In [17]:
movies = pd.read_csv("IMDb_All_Genres_etf_clean1.csv")

In [18]:
movies

,Movie_Title,Year,Director,Actors,Rating,Runtime(Mins),Censor,Total_Gross,main_genre,side_genre
0,Kantara,2022,Rishab Shetty,"Rishab Shetty, Sapthami Gowda, Kishore Kumar G...",9.3,148,UA,Gross Unkown,Action,"Adventure, Drama"
1,The Dark Knight,2008,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",9.0,152,UA,$534.86M,Action,"Crime, Drama"
2,The Lord of the Rings: The Return of the King,2003,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...",9.0,201,U,$377.85M,Action,"Adventure, Drama"
3,Inception,2010,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",8.8,148,UA,$292.58M,Action,"Adventure, Sci-Fi"
4,The Lord of the Rings: The Two Towers,2002,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...",8.8,179,UA,$342.55M,Action,"Adventure, Drama"
...,...,...,...,...,...,...,...,...,...,...
5557,Disaster Movie,2008,"Directors:Jason Friedberg, Aaron Seltzer","Carmen Electra, Vanessa Lachey, Nicole Parker,...",1.9,87,PG-13,$14.19M,Comedy,Sci-Fi
5558,The Hottie & the Nottie,2008,Tom Putnam,"Paris Hilton, Joel David Moore, Christine Laki...",1.9,91,PG-13,$0.03M,Comedy,Romance
5559,From Justin to Kelly,2003,Robert Iscove,"Kelly Clarkson, Justin Guarini, Katherine Bail...",1.9,81,PG,$4.92M,Comedy,"Musical, Romance"
5560,Superbabies: Baby Geniuses 2,2004,Bob Clark,"Jon Voight, Scott Baio, Vanessa Angel, Skyler ...",1.5,88,PG,$9.11M,Comedy,"Family, Sci-Fi"
5561,Cumali Ceber: Allah Seni Alsin,2017,Gökhan Gök,"Halil Söyletmez, Doga Konakoglu, Emre Keskin, ...",1.0,100,Not Rated,Gross Unkown,Comedy,Comedy

In [21]:
movies.columns

Index(['Movie_Title', 'Year', 'Director', 'Actors', 'Rating', 'Runtime(Mins)',
       'Censor', 'Total_Gross', 'main_genre', 'side_genre'],
      dtype='object')

In [24]:
pip install pickel

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pickel (from versions: none)
ERROR: No matching distribution found for pickel

In [26]:
import pickle

In [27]:
data  = pd.read_csv("top10K-TMDB-movies.csv")

In [28]:
pickle.dump(data,open("movie_list.pkl","wb"))